### ISSUE TITLE
Cannot reproduce experiment result from (Wang & Blei, 2011)

### ISSUE THREAD

**Issue by YuwenXiong** [Blei-Lab/ctr#4]
I cannot get the same result in the paper Collaborative Topic Modeling for Recommending Scientific articles. Please help!

I download ctr source code and lda-c source code from https://github.com/Blei-Lab, and use data from http://www.cs.cmu.edu/~chongw/data/citeulike/.

I set fixed alpha=0.005 and num_topics=200 for lda, and default parameter for ctr(no theta_opt, no lda_regression, a=1, b=0.01, lambda_u=0.01, lambda_v=100, learning_rate=-1, alpha_smooth=0, num_factors=200), and use lda's output(final.gamma, final.beta) for theta_init and beta_init. The mult.dat file I used for is from http://www.cs.cmu.edu/~chongw/data/citeulike/

Then I run ctr with cf-train-1-items.dat and cf-train-1-users.dat, and evaluate recall value with cf-test-1-users.dat, but I can only get 4.1% for recall@10 and 7.9% for recall@20.

Can you tell me what I was doing wrong? Thanks!

**Comment by lezorich** [comment]
Hi @Orpine , did you figure out what was happening? I can't reproduce the results either.
